export const LOG_WILL_IN_PROGRESS = "LOG_WILL_IN_PROGRESS"
export const LOG_IN_PROGRESS = 'LOG_IN_PROGRESS'
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'  
export const LOG_IN_FAILED = 'LOG_IN_FALED'
export const LOG_OUT_PROGRESS = 'LOG_OUT_PROGRESS'
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS'
export const LOG_OUT_FAILED = 'LOG_IN_FAILED'


export const REG_IN_PROGRESS = 'REG_IN_PROGRESS'
export const REG_SUCCESS = 'REG_SUCCESS'
export const REG_FAILED = 'REG_FAILED'

export const USER_AUTHORIZE = "USER_AUTHORIZE"
export const USER_AUTHORIZED = "USER_AUTHORIZED"
export const USER_UNAUTHORIZED = "USER_UNAUTHORIZED"

export const FILMS_WILL_LOAD = "FILMS_WILL_LOAD"
export const FILMS_LOADING = "FILMS_LOADING"
export const FILMS_LOADED = "FILMS_LOADED"
export const FILMDETAILS_WILL_LOAD = "FILMDETAILS_WILL_LOAD"
export const FILMDETAILS_LOADED = "FILMDETAILS_LOADED"
export const FILMSFROMCATEGORY_WILL_LOAD = "FILMSFROMCATEGORY_WILL_LOAD"

export const FILMCOMMENTS_WILL_LOAD = "FILMCOMMENT_WILL_LOAD"
export const FILMCOMMENTS_LOADED = "FILMCOMMENT_LOADED"

export const FILMCOMMENT_WILL_ADD = "FILMCOMMENT_WILL_ADD"
export const FILMCOMMENT_ADDED = "FILMCOMMENT_ADDED"