export const EMAIL_CHANGE = 'EMAIL_CHANGE'
export const PASSWORD_CHANGE = 'PASSWORD_CHANGE'
export const EMAIL_VALIDATE = 'EMAIL_VALIDATE'
export const PASSWORD_VALIDATE = 'PASSWORD_VALIDATE'
export const DATA_RESET = 'DATA_RESET';
export const DATA_SUBMIT = 'DATA_SUBMIT'